# Generated by Django 3.2.13 on 2022-05-30 19:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stratagem',
            name='created_dt',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2022, 5, 30, 19, 44, 30, 784213)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='stratagem',
            name='modified_dt',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
