# Generated by Django 3.2.13 on 2022-06-12 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20220612_1613'),
    ]

    operations = [
        migrations.AddField(
            model_name='stratagem',
            name='directory',
            field=models.CharField(blank=True, max_length=1024),
        ),
    ]
