# Generated by Django 3.2.13 on 2022-06-12 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_stratagem_directory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stratagem',
            name='directory',
        ),
        migrations.AddField(
            model_name='stratagem',
            name='params',
            field=models.JSONField(default=dict),
        ),
    ]
