# Generated by Django 3.2.13 on 2022-07-11 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_stratagem_kind'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stratagem',
            name='kind',
            field=models.CharField(choices=[('CLOJUREGRAPH1', 'ClojureGraph1'), ('PYTHONREFACTORING1', 'PythonRefactoring1'), ('WEBDASHBOARD1', 'WebDashboard1')], default='CLOJUREGRAPH1', max_length=32),
        ),
    ]
