# Generated by Django 3.2.13 on 2022-11-14 21:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_codesearch'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='codesearch',
            name='data',
        ),
        migrations.RemoveField(
            model_name='codesearch',
            name='grammar',
        ),
    ]
