# Generated by Django 3.2.13 on 2022-11-14 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_auto_20221114_2108'),
    ]

    operations = [
        migrations.AddField(
            model_name='codesearch',
            name='data',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='codesearch',
            name='grammar',
            field=models.TextField(blank=True, default=''),
        ),
    ]
