# Generated by Django 4.1.6 on 2023-02-07 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0013_fiddle"),
    ]

    operations = [
        migrations.AddField(
            model_name="fiddle",
            name="revision",
            field=models.PositiveBigIntegerField(default=1),
        ),
        migrations.AddField(
            model_name="fiddle",
            name="version",
            field=models.CharField(default="000", max_length=3),
        ),
        migrations.AlterField(
            model_name="fiddle",
            name="kind",
            field=models.CharField(
                choices=[("JSON_MATCHER", "JSON Matcher")], default=None, max_length=64
            ),
        ),
    ]
