# Generated by Django 4.1.6 on 2023-02-07 17:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0014_fiddle_revision_fiddle_version_alter_fiddle_kind"),
    ]

    operations = [
        migrations.RenameField(
            model_name="fiddle",
            old_name="revision",
            new_name="rev",
        ),
    ]
