# Generated by Django 4.1.6 on 2023-02-07 17:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0015_rename_revision_fiddle_rev"),
    ]

    operations = [
        migrations.AddField(
            model_name="fiddle",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="main.fiddle",
            ),
        ),
    ]
