# Generated by Django 4.1.6 on 2023-02-08 07:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0016_fiddle_parent"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="fiddle",
            name="session_id",
        ),
    ]
