# Generated by Django 4.1.6 on 2023-03-07 00:52

from django.db import migrations, models
import main.models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0017_remove_fiddle_session_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="fiddle",
            name="data",
            field=models.JSONField(default=main.models.getNone),
        ),
    ]
