# Generated by Django 4.1.6 on 2023-03-09 19:33

from django.db import migrations, models
import main.models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0018_alter_fiddle_data"),
    ]

    operations = [
        migrations.AlterField(
            model_name="fiddle",
            name="data",
            field=models.JSONField(blank=True, default=main.models.getNone, null=True),
        ),
    ]
