# Generated by Django 4.1.7 on 2023-07-20 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0021_log_alter_fiddle_kind"),
    ]

    operations = [
        migrations.AddField(
            model_name="log",
            name="data2",
            field=models.JSONField(blank=True, default=None, null=True),
        ),
    ]
