# Generated by Django 5.2 on 2025-05-22 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0024_alter_fiddle_kind"),
    ]

    operations = [
        migrations.CreateModel(
            name="RootedCopy",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name_from", models.CharField(max_length=1024)),
                ("name_to", models.CharField(max_length=1024)),
                ("fs_path", models.CharField(max_length=1024)),
                ("created_dt", models.DateTimeField(auto_now_add=True)),
                ("modified_dt", models.DateTimeField(auto_now=True)),
                ("files", models.TextField(blank=True, default="")),
                ("items", models.JSONField(blank=True, default=None, null=True)),
            ],
            options={
                "ordering": ["-modified_dt"],
            },
        ),
    ]
