# Generated by Django 5.2 on 2025-05-25 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0025_rootedcopy"),
    ]

    operations = [
        migrations.AddField(
            model_name="rootedcopy",
            name="cancelled_items",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="rootedcopy",
            name="parent_paths",
            field=models.JSONField(blank=True, default=None, null=True),
        ),
    ]
