# Generated by Django 5.2 on 2025-05-25 14:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0026_rootedcopy_cancelled_items_rootedcopy_parent_paths"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="rootedcopy",
            name="cancelled_items",
        ),
    ]
