# Generated by Django 5.2 on 2025-05-25 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0027_remove_rootedcopy_cancelled_items"),
    ]

    operations = [
        migrations.AddField(
            model_name="rootedcopy",
            name="cancelled_items",
            field=models.JSONField(blank=True, default=None, null=True),
        ),
    ]
