# Generated by Django 5.2 on 2025-05-26 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0028_rootedcopy_cancelled_items"),
    ]

    operations = [
        migrations.AddField(
            model_name="rootedcopy",
            name="full_paths",
            field=models.TextField(blank=True, default=""),
        ),
    ]
