# Generated by Django 5.2 on 2025-06-30 09:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0029_rootedcopy_full_paths"),
    ]

    operations = [
        migrations.CreateModel(
            name="CoolTraceProject",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=256)),
                ("fs_path", models.CharField(max_length=2048)),
                ("created_dt", models.DateTimeField(auto_now_add=True)),
                ("modified_dt", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name="rootedcopy",
            name="git_params",
            field=models.JSONField(blank=True, default=None, null=True),
        ),
        migrations.CreateModel(
            name="CoolTraceEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="main.cooltraceproject",
                    ),
                ),
            ],
        ),
    ]
