# Generated by Django 5.2 on 2025-11-10 18:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="MatcherProject",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name="MatcherNode",
            fields=[
                ("id", models.UUIDField(primary_key=True, serialize=False)),
                (
                    "what",
                    models.CharField(
                        blank=True, default=None, max_length=300, null=True
                    ),
                ),
                ("data", models.JSONField(blank=True, default=None, null=True)),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="matcher.matcherproject",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="MatcherStratagem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=300)),
                ("graph", models.JSONField(blank=True, default=None, null=True)),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="matcher.matcherproject",
                    ),
                ),
            ],
        ),
    ]
