# Generated by Django 5.2 on 2025-11-10 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("matcher", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="matcherproject",
            options={"ordering": ("order",)},
        ),
        migrations.AlterModelOptions(
            name="matcherstratagem",
            options={"ordering": ("order",)},
        ),
        migrations.AddField(
            model_name="matcherproject",
            name="order",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="matcherstratagem",
            name="order",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
