# Generated by Django 5.2 on 2025-11-10 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("matcher", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="matcherproject",
            name="order",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="matcherstratagem",
            name="order",
            field=models.IntegerField(default=0),
        ),
    ]
