# Generated by Django 5.2 on 2025-11-10 21:08

from django.db import migrations


def forwards_func(apps, schema_editor):
    MatcherProject = apps.get_model("matcher", "MatcherProject")
    MatcherStratagem = apps.get_model("matcher", "MatcherStratagem")
    for model in [MatcherProject, MatcherStratagem]:
        for order, item in enumerate(model.objects.all().order_by("id"), 1):
            item.order = order
            item.save(update_fields=['order'])


def reverse_func(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("matcher", "0002_alter_matcherproject_options_and_more"),
    ]

    operations = [
        migrations.RunPython(forwards_func, reverse_func),
    ]
