# Generated by Django 5.2 on 2025-11-10 20:57

from django.db import migrations

from matcher.models import MatcherProject


def forwards_func(apps, schema_editor):
    MatcherProject = apps.get_model("matcher", "MatcherProject")
    MatcherStratagem = apps.get_model("matcher", "MatcherStratagem")
    for i, matcher in enumerate(MatcherProject.objects.all(), 1):
        matcher.order = i
        matcher.save(update_fields=["order"])


def reverse_func(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("matcher", "0002_matcherproject_order_matcherstratagem_order"),
    ]

    operations = [
        migrations.RunPython(forwards_func, reverse_func),
    ]

