# Generated by Django 5.2 on 2025-11-10 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("matcher", "0003_auto_20251110_2108"),
    ]

    operations = [
        migrations.AddField(
            model_name="matcherproject",
            name="is_favourite",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="matcherstratagem",
            name="is_favourite",
            field=models.BooleanField(default=False),
        ),
    ]
