# Generated by Django 5.2 on 2025-11-16 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("matcher", "0004_matcherproject_is_favourite_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="matcherstratagem",
            name="graph",
        ),
        migrations.AddField(
            model_name="matcherstratagem",
            name="edges",
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AddField(
            model_name="matcherstratagem",
            name="nodes",
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
